import type { PriceItem } from "./types";

/** Демо-прайс (условные цены в ₽) для разработки и прикидок. */
export const DEMO_PRICES: PriceItem[] = [
  {
    id: "board-ldsp-18",
    category: "board",
    name: "ЛДСП 18 мм (корпус)",
    unit: "m2",
    price: 2800,
    note: "С учётом среднего декора",
    helpKey: "board_ldsp",
  },
  {
    id: "board-hdf",
    category: "board",
    name: "ХДФ задняя стенка",
    unit: "m2",
    price: 650,
    helpKey: "board_ldsp",
  },
  {
    id: "facade-film",
    category: "facade",
    name: "Фасад МДФ плёнка",
    unit: "m2",
    price: 9500,
    helpKey: "facade_film",
  },
  {
    id: "facade-enamel",
    category: "facade",
    name: "Фасад МДФ эмаль",
    unit: "m2",
    price: 18000,
    helpKey: "facade_enamel",
  },
  {
    id: "facade-veneer",
    category: "facade",
    name: "Фасад шпон",
    unit: "m2",
    price: 22000,
    helpKey: "facade_veneer",
  },
  {
    id: "facade-frame",
    category: "facade",
    name: "Фасад рамочный",
    unit: "m2",
    price: 14000,
    helpKey: "facade_frame",
  },
  {
    id: "edge-04",
    category: "edge",
    name: "Кромка ПВХ 0,4 мм",
    unit: "lm",
    price: 45,
    helpKey: "edge",
  },
  {
    id: "edge-2",
    category: "edge",
    name: "Кромка ПВХ 2 мм",
    unit: "lm",
    price: 120,
    helpKey: "edge",
  },
  {
    id: "hinge",
    category: "hardware",
    name: "Петля с доводчиком",
    unit: "pcs",
    price: 450,
    helpKey: "hinges",
  },
  {
    id: "runner",
    category: "hardware",
    name: "Направляющие шариковые (пара)",
    unit: "set",
    price: 1200,
    helpKey: "runners",
  },
  {
    id: "tandem",
    category: "hardware",
    name: "Тандембокс полный выдвиг",
    unit: "set",
    price: 6500,
    helpKey: "runners",
  },
  {
    id: "handle",
    category: "hardware",
    name: "Ручка мебельная",
    unit: "pcs",
    price: 350,
    helpKey: "handles",
  },
  {
    id: "leg",
    category: "hardware",
    name: "Опора регулируемая",
    unit: "pcs",
    price: 90,
    helpKey: "plinth",
  },
  {
    id: "countertop-hpl",
    category: "countertop",
    name: "Столешница пластик 38 мм",
    unit: "lm",
    price: 4500,
    helpKey: "countertop",
  },
  {
    id: "backsplash",
    category: "countertop",
    name: "Стеновая панель ЛДСП",
    unit: "lm",
    price: 2200,
    helpKey: "backsplash",
  },
  {
    id: "plinth",
    category: "other",
    name: "Цоколь",
    unit: "lm",
    price: 800,
    helpKey: "plinth",
  },
  {
    id: "false-panel",
    category: "other",
    name: "Фальшпанель",
    unit: "m2",
    price: 7500,
    helpKey: "false_panel",
  },
  {
    id: "led",
    category: "other",
    name: "Подсветка LED комплект",
    unit: "lm",
    price: 1800,
    helpKey: "lighting",
  },
  {
    id: "labor-cut",
    category: "labor",
    name: "Раскрой",
    unit: "m2",
    price: 450,
    helpKey: "cutting",
  },
  {
    id: "labor-edge",
    category: "labor",
    name: "Кромление (работа)",
    unit: "lm",
    price: 80,
    helpKey: "edging_labor",
  },
  {
    id: "labor-assembly",
    category: "labor",
    name: "Сборка корпусов",
    unit: "lm",
    price: 3500,
    helpKey: "assembly",
  },
  {
    id: "labor-delivery",
    category: "labor",
    name: "Доставка",
    unit: "job",
    price: 8000,
    helpKey: "delivery",
  },
  {
    id: "labor-install",
    category: "labor",
    name: "Монтаж",
    unit: "lm",
    price: 4500,
    helpKey: "installation",
  },
  {
    id: "tall-surcharge",
    category: "other",
    name: "Доплата за пенал",
    unit: "pcs",
    price: 25000,
    helpKey: "tall_unit",
  },
  {
    id: "appliance-surcharge",
    category: "other",
    name: "Доплата за нишу техники",
    unit: "pcs",
    price: 8000,
    helpKey: "appliance",
  },
];

export function priceById(
  prices: PriceItem[],
  id: string,
): PriceItem | undefined {
  return prices.find((p) => p.id === id);
}
