/**
 * Курируемые ставки движка сметы из master_price.xlsx (Ренессанс, 03.07.2026).
 * Полный каталог (~4893 строк) импортируется отдельно скриптом.
 */
import type { DemoPriceSeed } from "./demo-prices";

export const RENAISSANCE_ENGINE_DEFAULTS: DemoPriceSeed[] = [
  {
    key: "board-ldsp-18",
    category: "board",
    name: "ЛДСП кухни складская программа, кромка 1 мм",
    unit: "m2",
    price: 2520,
    note: "Ренессанс · ЛДСП складская программа",
    helpKey: "board_ldsp",
  },
  {
    key: "board-hdf",
    category: "board",
    name: "ХДФ",
    unit: "m2",
    price: 800,
    note: "Ренессанс · Прочие материалы",
    helpKey: "board_ldsp",
  },
  {
    key: "facade-film",
    category: "facade",
    name: "МДФ Плёнка (ВДМ) 16мм 1 группа, 2 стороны",
    unit: "m2",
    price: 8290,
    note: "Ренессанс · Группы Плёнка МДФ",
    helpKey: "facade_film",
  },
  {
    key: "facade-enamel",
    category: "facade",
    name: "МДФ Эмаль матовая 16мм (мыло)",
    unit: "m2",
    price: 11850,
    note: "Ренессанс · МДФ ЭМАЛЬ 16мм",
    helpKey: "facade_enamel",
  },
  {
    key: "facade-veneer",
    category: "facade",
    name: "Кромка/ориентир шпон (ставка кромки НШ 1гр; фасад уточнять)",
    unit: "lm",
    price: 290,
    note: "В прайсе шпон часто как кромка/спецзаказ — проверять категорию фасада",
    helpKey: "facade_veneer",
  },
  {
    key: "facade-frame",
    category: "facade",
    name: "Алюмин. профиль на фасады (узкий)",
    unit: "lm",
    price: 210,
    note: "Ренессанс · АЛЮМИНИЕВЫЙ ПРОФИЛЬ ДЛЯ ФАСАДОВ",
    helpKey: "facade_frame",
  },
  {
    key: "edge-04",
    category: "edge",
    name: "Кромка 0,8х19 (ближайший тонкий аналог; 0,4 в прайсе нет)",
    unit: "lm",
    price: 80,
    note: "Ренессанс · КРОМКА",
    helpKey: "edge",
  },
  {
    key: "edge-2",
    category: "edge",
    name: "Кромка ПВХ 2х19 мм",
    unit: "lm",
    price: 100,
    note: "Ренессанс · КРОМКА",
    helpKey: "edge",
  },
  {
    key: "hinge",
    category: "hardware",
    name: "Петля Boyard накладная с доводчиком",
    unit: "pcs",
    price: 190,
    note: "Ренессанс · ПЕТЛИ",
    helpKey: "hinges",
  },
  {
    key: "runner",
    category: "hardware",
    name: "Направляющие Boyard ПВШ DB 3501 на 450 мм",
    unit: "set",
    price: 260,
    note: "Ренессанс · НАПРАВЛЯЮЩИЕ ДЛЯ ЯЩИКОВ ПВШ",
    helpKey: "runners",
  },
  {
    key: "tandem",
    category: "hardware",
    name: "Movento Blum c BLUMOTION S 40кг гл.450",
    unit: "set",
    price: 7510,
    note: "Ренессанс · TANDEM BLUM MOVENTO",
    helpKey: "runners",
  },
  {
    key: "handle",
    category: "hardware",
    name: "Ручка-скоба в тон",
    unit: "pcs",
    price: 10,
    note: "Ренессанс · РУЧКИ (мин. ставка; каталог огромный)",
    helpKey: "handles",
  },
  {
    key: "tip-on",
    category: "hardware",
    name: "Толкатель Push-to-Open Boyard AMF13",
    unit: "pcs",
    price: 160,
    note: "Ренессанс · ПЕТЛИ И КОМПЛЕКТУЮЩИЕ",
    helpKey: "handles",
  },
  {
    key: "leg",
    category: "hardware",
    name: "Опора h22 мм",
    unit: "pcs",
    price: 60,
    note: "Ренессанс · НОЖКИ",
    helpKey: "plinth",
  },
  {
    key: "countertop-hpl",
    category: "countertop",
    name: "Столешница Egger 38 мм 1 группа",
    unit: "lm",
    price: 6880,
    note: "Ренессанс · СТОЛЕШНИЦЫ EGGER",
    helpKey: "countertop",
  },
  {
    key: "backsplash",
    category: "countertop",
    name: "Стеновая панель Arpa 1 группа",
    unit: "m2",
    price: 6730,
    note: "Ренессанс · ARPA (без кромки); в смете единица м²",
    helpKey: "backsplash",
  },
  {
    key: "plinth",
    category: "other",
    name: "Цоколь ПВХ №1–4 прямой (Ренессанс)",
    unit: "lm",
    price: 1290,
    note: "Ренессанс · МДФ БАГЕТ/БАЛЮСТРАДА",
    helpKey: "plinth",
  },
  {
    key: "false-panel",
    category: "other",
    name: "МДФ Плёнка 16мм 1 группа (как фальшпанель)",
    unit: "m2",
    price: 8290,
    note: "Та же ставка, что facade-film",
    helpKey: "false_panel",
  },
  {
    key: "led",
    category: "other",
    name: "Профиль + рассеиватель под LED (ориентир комплекта)",
    unit: "lm",
    price: 210,
    note: "Ренессанс · паз под подсветку 210; полный комплект дороже — уточнять",
    helpKey: "lighting",
  },
  {
    key: "glass-corrugated",
    category: "facade",
    name: "Стекло/наполнение — уточнять по разделу СТЁКЛА",
    unit: "m2",
    price: 3000,
    note: "Консервативный ориентир; сверять конкретный артикул",
    helpKey: "facade_frame",
  },
  {
    key: "labor-cut",
    category: "labor",
    name: "Раскрой (в прайсе нет явной ставки — внутреннее допущение)",
    unit: "m2",
    price: 450,
    note: "requires_confirmation · нет прямой строки в master_price",
    helpKey: "cutting",
  },
  {
    key: "labor-edge",
    category: "labor",
    name: "Кромление работа (допущение)",
    unit: "lm",
    price: 80,
    note: "requires_confirmation · нет прямой строки",
    helpKey: "edging_labor",
  },
  {
    key: "labor-assembly",
    category: "labor",
    name: "Сборка корпусов (допущение)",
    unit: "lm",
    price: 3500,
    note: "requires_confirmation",
    helpKey: "assembly",
  },
  {
    key: "labor-delivery",
    category: "labor",
    name: "Доставка (допущение)",
    unit: "job",
    price: 8000,
    note: "requires_confirmation",
    helpKey: "delivery",
  },
  {
    key: "labor-install",
    category: "labor",
    name: "Монтаж (допущение)",
    unit: "lm",
    price: 4500,
    note: "requires_confirmation",
    helpKey: "installation",
  },
  {
    key: "labor-measure",
    category: "labor",
    name: "Замер (допущение)",
    unit: "job",
    price: 5000,
    note: "requires_confirmation",
    helpKey: "assembly",
  },
  {
    key: "risk-buffer",
    category: "other",
    name: "Запас на риски объекта",
    unit: "job",
    price: 15000,
    note: "Внутреннее консервативное допущение Mebel-LAB",
    helpKey: "margin",
  },
  {
    key: "tall-surcharge",
    category: "other",
    name: "Доплата за пенал (допущение)",
    unit: "pcs",
    price: 25000,
    note: "requires_confirmation",
    helpKey: "tall_unit",
  },
];
